### ISSUE TITLE
HTML değişikliklerinden etkilenmiyor

### ISSUE THREAD

**Issue by uykalkan** [sefatunckanat/empty-frontend-template#1]
Ionic'te html veya js değişiklikleri olunca browser'a refresh atıyordu. Öyle bir şey nasıl yapılabilir ki.

Mesela şöyle bir şey var

`gulp.watch("src/*.html").on('change', browserSync.reload);`

Ama uyguladığım zaman bir acayip çalışıyor. Refresh atıyor ama son değişiklik gelmiyor.

@sefatunckanat

**Comment by sefatunckanat** [comment]
[#c41cd9d](https://github.com/sefatunckanat/empty-frontend-template/commit/cc7aedc45813c00b73da41186ccc8d341d39993d#diff-b9e12334e9eafd8341a6107dd98510c9) commitinde düzeltme yapıldı. Şuanda HTML üzerindeki değişikliklerde de Browser sync yenileme yapıyor. 
Yeni bir task eklenirken mantık olarak hangi sıraya konulması gerektiğinin önemi çok zira en sona alınsaydı kod dediğiniz gibi daha farklı sonuçlar elde edilirdi.
